all:
	$(CXX) main.cpp -o main_debug -g -O0 --std=c++11
	$(CXX) main.cpp -o main_release0 -O0 --std=c++11
	$(CXX) main.cpp -o main_release1 -O1 --std=c++11
	$(CXX) main.cpp -o main_release2 -O2 --std=c++11
	$(CXX) main.cpp -o main_release3 -O3 --std=c++11
